# Generated by Django 6.0.3 on 2026-03-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivebooks',
            name='cover_image',
            field=models.ImageField(upload_to='DriveBooks/cover_image/'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
