# Generated by Django 6.0.3 on 2026-03-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_drivebooks_cover_image_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
