# Generated by Django 6.0.3 on 2026-03-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
