# Generated by Django 6.0.3 on 2026-03-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_category_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_pic',
        ),
    ]
