# Generated by Django 6.0.3 on 2026-03-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_author_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivebooks',
            name='cover_image',
            field=models.ImageField(upload_to='books/cover_image/'),
        ),
    ]
