# Generated by Django 6.0.3 on 2026-03-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_drivebooks_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivebooks',
            options={'verbose_name': 'DriveBooks', 'verbose_name_plural': 'Books'},
        ),
    ]
